name: ci

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: tag number
        run : echo ${{ github.event.release.tag_name }}
      -
        name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dukun/TorrServer
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: dukun
          password: ${{ secrets.TOKEN }}
      - 
        name: set lower case owner name
        run: |
          echo "REG_REPO=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'
      - 
        name: CHECK ENVS
        run: |
          echo ${{ env.REG_REPO }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7